README.md

Since there seems to be only an AUR package (at least judging from the README), I just created an RPM to ease the installation and upgrade for Fedora and EPEL users. This PR simply mentions it in the README alongside the AUR one.

Add Copr repo to README.md

---

install.sh

This allows overriding shell version in installer via the "gnomever"
environment variable. This is needed when installing in developer builds
of GNOME, where the result of calling "gnome-shell --version" may not
match the versions available in this repository, thus failing to build
shell theme.

Install: Allow GNOME Shell version override

---

install.sh

running in shell
```sh
SIZE_VARIANTS="-compact" COLOR_VARIANTS="," THEME_DIR_BASE=~/.themes/test-theme ./install.sh
```
will install only normal color variant of compact theme into `~/.themes/` dir,
ie `~/.themes/test-theme-compact`
running `install.sh` without arguments still produces the same result

feat(install.sh): allow to configure installation options via env vars

---

README.md

I had to install `libxml2-utils` on a clean install of Ubuntu 17.10 (artful). I don't know if this is required for other version/distros.

Add libxml2-utils to dependencies.

---

install.sh

Installation is failing if the install script is not invoke from the source directory. Fix that by always accessing source files by their full path ($srcdir)

install.sh: Access source files by full path

---

README.md

* Materia version: any
* GTK+ 3 version: any
* Distribution: Arch Linux, any version
* Desktop environment: any
* Related application: `yaourt`, `makepkg`. None using GTK itself
* Steps to reproduce: none
* Screenshot(s): none
AUR helpers are [not supported](https://wiki.archlinux.org/index.php/AUR_helpers).
In addition, `yaourt` is [not actively maintained](https://wiki.archlinux.org/index.php/AUR_helpers#Inactive) nor is it recommended to use due to it's insecure and unreliable nature.
This PR updates the Arch Linux installation instructions as per [the AUR installation instructions](https://wiki.archlinux.org/index.php/Arch_User_Repository#Installing_packages).

update Arch installation instructions

---

change_color.sh
src/_sass/_colors.scss.template

Hey here is my little attempt to improve coloring of dark materia themes.
@actionless would be nice if you could review this. Dark themes look now better in my opinion if the new value is set to dark. IMPORTANT Until we implement `is_dark`nothing should change on the user side if the new variable is not set or set to light/standard.
* Created new value MATERIA_COLOR_VARIANT which should be light/dark/standard, default is set to light, so that nothing changes for oomox users or if the value is not set.
* Created new seds for recoloring gtkrc-dark only used if MATERIA_COLOR_VARIANT=dark
* Removed GTK3_GENERATE_DARK (experimental, could leave a placeholder)
* Removed MATERIA_MENUBAR_STYLE (experimental, could leave a placeholder)
* Adapted the if clauses for every case light/dark/standard
* …

Improving change_color.sh and _color.scss.template for darker themes

---

src/_sass/gtk/_apps-3.18.scss
src/_sass/gtk/_apps-3.20.scss
src/_sass/gtk/_apps-3.22.scss
src/_sass/gtk/apps/_nemo.scss
src/gtk/3.18/gtk-dark.css
src/gtk/3.18/gtk-light.css
src/gtk/3.18/gtk.css
src/gtk/3.20/gtk-compact.css
src/gtk/3.20/gtk-dark-compact.css
src/gtk/3.20/gtk-dark.css
src/gtk/3.20/gtk-light-compact.css
src/gtk/3.20/gtk-light.css
src/gtk/3.20/gtk.css
src/gtk/3.22/gtk-compact.css
src/gtk/3.22/gtk-dark-compact.css
src/gtk/3.22/gtk-dark.css
src/gtk/3.22/gtk-light-compact.css
src/gtk/3.22/gtk-light.css
src/gtk/3.22/gtk.css

Hi,
To go with the Cinnamon theme I thought it was worth making Nemo a little prettier under Materia. The PR colorises the side bar and tweaks background background-colors in dual pane view so the active pane can be distinguished visibility. GTK 3.18 and GTK 3.22 have been tested.
Edit - I guess the GTK .css hadn't been updated following previous commits to master?
Before...
After

GTK3, 3.20, 3.22 - Add theming for Nemo (Cinnamon file and desktop manager)

---

src/_sass/cinnamon/_common.scss
src/_sass/cinnamon/_extends.scss

Closes #310
* Cinnamon - add support for Cinnamon 4 grouped window list
* Cinnamon - add support for new styles used in Cinnamon 4 overview
* Cinnamon - add support for alternative Cinnamon 4 stock menu
* Cinnamon - tweaked use of padding and margins in panel items to avoid icon distortion for user defined panel icon sizes in Cinnamon 4
* Cinnamon - bugfix - fixed workspace-overview in vertical panels
* Cinnamon - bugfix - fixed popup-menu-item spacing/padding for right click context menu's in panel.
* Cinnamon - bugfix - add a little padding between icon + label in the window-list applet

Cinnamon4 update

---

README.md

I've recently changed the name of my materia package from `materia-them` to `materia-gtk-theme`. It's mainly to make a distinction with `materia-kde` that I'm also packaging, but it also makes materia have the same package name for every distro; I should have done that earlier.

README.md: Update Fedora package name

---

install.sh

fix(install.sh): bash var fallback doesn't work as expected with bash array with an empty string: `ARR=('')`

---

install.sh

initialize `colors` and `sizes` as an empty array in order to avoid `unbound variable` when running `install.sh` without  `--color` and `--size` arguments.

Fix install.sh (#416) unbound variable

---

src/_sass/gtk/apps/_gnome-3.22.scss
src/gtk/3.0/gtk-compact.css
src/gtk/3.0/gtk-dark-compact.css
src/gtk/3.0/gtk-dark.css
src/gtk/3.0/gtk-light-compact.css
src/gtk/3.0/gtk-light.css
src/gtk/3.0/gtk.css

It's not that bad actually, but not good either. [Upstream issue](https://gitlab.gnome.org/GNOME/evince/issues/1043). Documents app also uses evview, (iirc, no hardcoded values there - bg/fg colors are inherited from .view), so background-color also need to be set. 
before/after:  
before/after:  
Also, i accidentally pressed fullscreen button, and looks like page-count/zoom-value enties lacks solid background (i assume you intentionally make top bar transparent).

gtk: Fix selected text color in Evince

---

src/chrome/render-asset.sh
src/gtk-2.0/render-asset.sh
src/gtk/render-asset.sh

This prevents the scripts from exiting if `rendersvg` is installed but
`inkscape` is not.
And make sure `inkscape` is available when `rendersvg` is unavailable.

scripts: Carefully check if inkscape exists

---

README.md

Since there's a package in the official repository now, link to that instead of the copr repository.

README.md: Update installation instructions for Fedora

---

src/cinnamon/meson.build
src/gnome-shell/meson.build
src/gtk-3.0/meson.build
src/gtk-4.0/meson.build

I'm getting error on building:
```
src/cinnamon/meson.build:55:8: ERROR: add_install_script args must be strings
```
- ubuntu 20.04 (Focal Fossa)
- meson: v0.53.2 (retrieved from focal repositories)
- sassc: v3.6.1
- libsass: v3.6.3
- sass2scss: v1.1.1
- sass: v3.5
1. `git clone https://github.com/nana-4/materia-theme.git`
2. `cd materia-theme`
3. `meson _build -Dprefix="$HOME/.local"`
I'm getting following error:
```
The Meson build system
Version: 0.53.2
Source dir: /home/ponpon/Materia
Build dir: /home/ponpon/Materia/_build
Build type: native build
Project name: materia-theme
Project version: 20200916
Host machine cpu family: x86_64
Host machine cpu: x86_64
Program sassc found: YES (/usr/bin/sassc)
Program sh found: YES (/usr/bin/sh)
Configuring Materia.index.theme using configuration …
```

Fix build error on Ubuntu 20.04: "add_install_script args must be strings"

---

change_color.sh

We are going to drop support for `install.sh`.
This replaces `install.sh` with `meson` in `change_color.sh`.
See https://github.com/nana-4/materia-theme/issues/554

change_color.sh: Replace install.sh with meson

---

.gitignore
HACKING.md
INSTALL.md
meson.build
package-lock.json
package.json
parse-sass.sh
src/cinnamon/meson.build
src/gnome-shell/meson.build
src/gtk-3.0/meson.build
src/gtk-4.0/meson.build

LibSass and SassC have been deprecated. Let's migrate to Dart Sass
as recommended by the Sass team. See:
https://sass-lang.com/blog/libsass-is-deprecated
Closes https://github.com/nana-4/materia-theme/issues/553

build: Migrate from sassc to dart-sass

---

parse-sass.sh
render-assets.sh
snapshot.sh
src/chrome/render-asset.sh
src/chrome/render-assets.sh
src/gtk-2.0/render-asset.sh
src/gtk-2.0/render-assets.sh
src/gtk-3.0/render-asset.sh
src/gtk-3.0/render-assets.sh

Make build on systems where bash may be outside of /bin reproducible.
By convention and [portability](https://en.wikipedia.org/w/index.php?title=Shebang_(Unix)&oldid=878552871#Portability)  is used #!/usr/bin/env bash.

build: shebang  portability and fix build on *nix systems

---

src/gtk-3.0/sass/apps/_misc.scss

This PR ports the patch found at https://github.com/heldplayer/materia-theme-custom/commit/93af85f1c775745e46f92673bc55edf39b179579
I've used materia for many years, I love the theme. I encountered this glitch which I found to be really annoying for the better part of 2022. Luckily I found this patch (credit to the author @heldplayer) which fixes the issue.

gtk/chromium: Fix border between toolbar and page content being transparent
