src/gtk-2.0/render-asset.sh
src/gtk-2.0/render-assets.sh
src/gtk-3.0/gtk-common/render-asset.sh
src/gtk-3.0/gtk-common/render-assets.sh

Sequentially:
134.22 seconds
In parallel:
92.91 seconds

feat(gtk2, gtk3: render-assets): use `parallel` if installed

---

change_color.sh
scripts/darker.sh
scripts/mix.sh

To test in `bash`:
```bash
$ ./change_color.sh -o my-test-theme <(echo -e "BG=d8d8d8\nFG=101010\nMENU_BG=3c3c3c\nMENU_FG=e6e6e6\nSEL_BG=ad7fa8\nSEL_FG=ffffff\nTXT_BG=ffffff\nTXT_FG=1a1a1a\nBTN_BG=f5f5f5\nBTN_FG=111111\n")
```
To test in `fish`:
```fish
$ ./change_color.sh -o my-test-theme (echo -e "BG=d8d8d8\nFG=101010\nMENU_BG=3c3c3c\nMENU_FG=e6e6e6\nSEL_BG=ad7fa8\nSEL_FG=ffffff\nTXT_BG=ffffff\nTXT_FG=1a1a1a\nBTN_BG=f5f5f5\nBTN_FG=111111\n" | psub)
```

feat(change_color.sh): script to generate theme with custom color

---

change_color.sh
src/gtk-2.0/main.rc.hidpi
src/gtk-2.0/render-asset.sh

feat(gtk2): hidpi support

---

change_color.sh

fix(change_color): update for a new name

---

README.md

Update package names in README

---

change_color.sh

see https://github.com/actionless/oomox/issues/94#issuecomment-344633105

feat(change_color.sh): add $MATERIA_MENUBAR_STYLE

---

change_color.sh

fix(change_color): don't attempt to rename the theme if its name is already good

---

change_color.sh

it was still not fine after the latest fix: https://github.com/actionless/oomox/issues/94#issuecomment-351302570

fix(change_color): do more precise substitution

---

change_color.sh

it's not needed anymore after _colors.scss is common now

fix(change_color): remove workaround for gnome shell

---

change_color.sh
src/_sass/_colors.scss.template

re https://github.com/nana-4/materia-theme/issues/210

feat(change_color, colors.scss): use scss file with templated colors instead of replacing colors in the original scss file

---

README.md

The problem is resolved. The repository was created anew.
Close #223 #215 #228

README.md: Replacing the installation package #44

---

install.sh

I updated the installation script `(./install.sh)` to optionally allow installing GDM theme.
Please have a look and let me know if something need to be changed. I added `install_gdm() ` function to make sure GDM them will run only once after the original installation finished.
How can you install GDM theme? here is some examples:
sudo ./install.sh --gdm
sudo ./install.sh -n mytheme -d ~/.theme --gdm
sudo ./install  -c light -s standard --gdm

Added --gdm to optionally install GDM theme

---

README.md

i am not sure if it make actually more clear or not :D 
but i was just thinking what after roundness changed in the new Materia release i can expect number of people asking "how to return old square buttons?" (the same as it was when default colors got changed)

doc(readme): make it easier for users to understand why oomox is needed

---

README.md

The package is maintained by the community and the core team of Solus, both of them can make updates but all package updates are reviewed by the Solus core team before they get merged. It is freedom for anyone to submit updates, but they are safe and checked before they get sent to the build server. It has the benefits of the AUR but in a safe and reliable way.

Add the Solus package to the list

---

src/_sass/gnome-shell/_common-3.32.scss
src/gnome-shell/3.32/gnome-shell-compact.css
src/gnome-shell/3.32/gnome-shell-dark-compact.css
src/gnome-shell/3.32/gnome-shell-dark.css
src/gnome-shell/3.32/gnome-shell-light-compact.css
src/gnome-shell/3.32/gnome-shell-light.css
src/gnome-shell/3.32/gnome-shell.css

gnome-shell: Update toggle-switch style

---

src/_sass/_colors.scss.template

Fix issues in _colors.scss.template

---

src/_sass/gtk/_common-3.20.scss

Maybe fix #419 -- I'm not 100% sure how the SCSS is laid out, but this seems to be the way to do it, as best as I can tell.

add &.osd to label

---

change_color.sh

exemple:
`./change_colors -d ~/my-test-dir ...`
By default nothing was changed

Added custom install path option to change_color.sh

---

src/chrome/render-asset.sh
src/gtk-2.0/render-asset.sh
src/gtk/render-asset.sh

Post beta change?
Thanks for the awesome project btw! :smiley:

Inkscape 1.0's --export-file option changed to --export-filename.

---

change_color.sh
src/chrome/render-asset.sh
src/gtk-2.0/render-asset.sh
src/gtk/render-asset.sh

feat(change_color, *: render-assets): add FORCE_INKSCAPE env var
